export const mantenimientoTipos = [
    { id: '1', tipo: 'PREVENTIVO', descripcion: 'REVISION GENERAL DEL MOTOR', frecuencia: true, kilometraje: false },
    { id: '2', tipo: 'PREVENTIVO', descripcion: 'CAMBIO DE ACEITE Y FILTRO DE ACEITE', frecuencia: false, kilometraje: true },
    { id: '3', tipo: 'PREVENTIVO', descripcion: 'CAMBIO DE FILTRO DE AIRE', frecuencia: true, kilometraje: true },
    { id: '4', tipo: 'PREVENTIVO', descripcion: 'INSPECCIÓN DE LA CORREA DE DISTRIBUCIÓN', frecuencia: true, kilometraje: false },
    { id: '5', tipo: 'PREVENTIVO', descripcion: 'INSPECCIÓN DEL SISTEMA DE FRENOS', frecuencia: true, kilometraje: false },
    { id: '6', tipo: 'PREVENTIVO', descripcion: 'INSPECCIÓN DEL SISTEMA DE SUSPENSIÓN', frecuencia: true, kilometraje: false },
    { id: '7', tipo: 'PREVENTIVO', descripcion: 'MANTENIMIENTO DE LA BATERÍA', frecuencia: true, kilometraje: false },
    { id: '8', tipo: 'PREVENTIVO', descripcion: 'MANTENIMIENTO DEL SISTEMA DE COMBUSTIBLE', frecuencia: true, kilometraje: false },
    { id: '9', tipo: 'PREVENTIVO', descripcion: 'MANTENIMIENTO DEL SISTEMA DE DIRECCIÓN', frecuencia: true, kilometraje: false },
    { id: '10', tipo: 'PREVENTIVO', descripcion: 'REVISON DE BUJIAS, CABLES Y CORREAS', frecuencia: true, kilometraje: false },
    { id: '11', tipo: 'PREVENTIVO', descripcion: 'REVISIÓN DE AMORTIGUADORES', frecuencia: true, kilometraje: false },
    { id: '12', tipo: 'PREVENTIVO', descripcion: 'REVISIÓN DE LUCES', frecuencia: true, kilometraje: false },
    { id: '13', tipo: 'PREVENTIVO', descripcion: 'REVISIÓN DEL DISPOSITIVO DE ACOPLAMIENTO', frecuencia: true, kilometraje: false },
    { id: '14', tipo: 'PREVENTIVO', descripcion: 'REVISIÓN DEL SISTEMA DE ADMISIÓN, MANGUERAS Y TUBERÍAS', frecuencia: true, kilometraje: false },
    { id: '15', tipo: 'PREVENTIVO', descripcion: 'REVISIÓN DEL SISTEMA DE ESCAPE', frecuencia: true, kilometraje: false },
    { id: '16', tipo: 'PREVENTIVO', descripcion: 'SERVICIO COMPLETO DE MANTENIMIENTO AUTOMOTRIZ', frecuencia: true, kilometraje: false },
    { id: '17', tipo: 'PREVENTIVO', descripcion: 'VERIFICACIÓN DE NEUMÁTICOS', frecuencia: true, kilometraje: false },
    { id: '18', tipo: 'PREVENTIVO', descripcion: 'VERIFICACIÓN DE NIVELES DE FLUIDOS', frecuencia: true, kilometraje: false },
    { id: '19', tipo: 'PREVENTIVO', descripcion: 'VERIFICACIÓN DEL FUNCIONAMIENTO DEL MOTOR', frecuencia: true, kilometraje: false },
    { id: '20', tipo: 'PREVENTIVO', descripcion: 'VERIFICACIÓN DEL SISTEMA DE TRANSMISIÓN', frecuencia: true, kilometraje: false },
    { id: '21', tipo: 'PREVENTIVO', descripcion: 'VERIFICACION DEL AIRE ACONDICIONADO', frecuencia: true, kilometraje: false },
    { id: '22', tipo: 'PREVENTIVO', descripcion: 'CAMBIO DE ACEITE CAJA', frecuencia: false, kilometraje: true },
    { id: '23', tipo: 'PREVENTIVO', descripcion: 'CAMBIO DE ACEITE CORONA', frecuencia: false, kilometraje: true },
    { id: '24', tipo: 'PREVENTIVO', descripcion: 'CAMBIO DE ACEITE RETARDE', frecuencia: false, kilometraje: true },
    { id: '25', tipo: 'PREVENTIVO', descripcion: 'CAMBIO FILTRO DE DISPARADOR', frecuencia: false, kilometraje: true },
    { id: '26', tipo: 'PREVENTIVO', descripcion: 'ENGRASE GENERAL', frecuencia: true, kilometraje: false },
    { id: '27', tipo: 'PREVENTIVO', descripcion: 'REGULADA DE FRENOS', frecuencia: true, kilometraje: false },
    { id: '28', tipo: 'PREVENTIVO', descripcion: 'MANTENIMIENTO DE ALTERNADOR', frecuencia: true, kilometraje: false },
    { id: '29', tipo: 'PREVENTIVO', descripcion: 'REVISION DEL SISTEMA DE REFRIGERACION', frecuencia: true, kilometraje: false },
    { id: '30', tipo: 'PREVENTIVO', descripcion: 'BUJES DE TENSOR DEL TRUCK', frecuencia: true, kilometraje: false },
    { id: '31', tipo: 'PREVENTIVO', descripcion: 'RODAMIENTOS', frecuencia: true, kilometraje: false },
    { id: '32', tipo: 'PREVENTIVO', descripcion: 'RETENES', frecuencia: true, kilometraje: false },
    { id: '33', tipo: 'PREVENTIVO', descripcion: 'REVISION DE VIGIA', frecuencia: true, kilometraje: false },
    { id: '34', tipo: 'PREVENTIVO', descripcion: 'REVISION GENERAL MECANICA', frecuencia: true, kilometraje: false },
    { id: '35', tipo: 'PREVENTIVO', descripcion: 'REVISION GENERAL ELECTRICO', frecuencia: true, kilometraje: false },
    { id: '36', tipo: 'PREVENTIVO', descripcion: 'REVISION GENERAL LLANTERO', frecuencia: true, kilometraje: false },

    // Agregar al final del array existente
    { id: '100', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE LLANTAS', frecuencia: true, kilometraje: false },
    { id: '101', tipo: 'CORRECTIVO', descripcion: 'REPARACION DE TRANSMISION Y DIRECCION', frecuencia: true, kilometraje: false },
    { id: '102', tipo: 'CORRECTIVO', descripcion: 'CORRECTIVO DEL SISTEMA DE A/C', frecuencia: true, kilometraje: false },
    { id: '103', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE BATERIAS', frecuencia: true, kilometraje: false },
    { id: '104', tipo: 'CORRECTIVO', descripcion: 'TRABAJOS DE LATONERIA Y PINTURAS', frecuencia: true, kilometraje: false },
    { id: '105', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE PIEZAS', frecuencia: true, kilometraje: false },
    { id: '106', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE TURBINAS', frecuencia: true, kilometraje: false },
    { id: '107', tipo: 'CORRECTIVO', descripcion: 'CAMBIO BALACHAS TRASERAS', frecuencia: true, kilometraje: false },
    { id: '108', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE CAÑERIA DE AIRE FRENO DEL. DER.', frecuencia: true, kilometraje: false },
    { id: '109', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE BALACHAS AL TRUQUE', frecuencia: true, kilometraje: false },
    { id: '110', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE AMORTIGUADOR IZQ TRUQUE', frecuencia: true, kilometraje: false },
    { id: '111', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE MOTOR LIMPIA PARABRISAS', frecuencia: true, kilometraje: false },
    { id: '112', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE PIEZAS ELECTRICAS', frecuencia: true, kilometraje: false },
    { id: '113', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE AMORTIGUADORES', frecuencia: true, kilometraje: false },
    { id: '114', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE REPUESTOS', frecuencia: true, kilometraje: false },
    { id: '115', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE TERMOSTATO', frecuencia: true, kilometraje: false },
    { id: '116', tipo: 'CORRECTIVO', descripcion: 'CAMBIO LLANTAS RECAHUCHUTADAS TRANS 2 DER', frecuencia: true, kilometraje: false },
    { id: '117', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE BARRA ESTABILIZADORA', frecuencia: true, kilometraje: false },
    { id: '118', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE GLOBOS DE AIRE', frecuencia: true, kilometraje: false },
    { id: '119', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE CORREAS', frecuencia: true, kilometraje: false },
    { id: '120', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE DISCO Y PRENSA', frecuencia: true, kilometraje: false },
    { id: '121', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE ALTERNADOR', frecuencia: true, kilometraje: false },
    { id: '122', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE COMPRESOR DE AIRE', frecuencia: true, kilometraje: false },
    { id: '123', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE ALTERNADOR', frecuencia: true, kilometraje: false },
    { id: '124', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE FILTRO DEO AIRE', frecuencia: true, kilometraje: false },
    { id: '125', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE FILTRO SECANTE', frecuencia: true, kilometraje: false },
    { id: '126', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE CAÑERIAS DE AIRE DE FRENO', frecuencia: true, kilometraje: false },
    { id: '127', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE CHICOTILLO A LA CAJA', frecuencia: true, kilometraje: false },
    { id: '128', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE LANTAS RECAHUCHUTADAS', frecuencia: true, kilometraje: false },
    { id: '129', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE BALATAS', frecuencia: true, kilometraje: false },
    { id: '130', tipo: 'CORRECTIVO', descripcion: 'CAMBIO DE ALTERNADOR DE MOTOR', frecuencia: true, kilometraje: false },

    { id: '200', tipo: 'PREDICTIVO', descripcion: 'MONITOREO EN LA VIBRACIONES DEL MOTOR', frecuencia: true, kilometraje: false },
    { id: '201', tipo: 'PREDICTIVO', descripcion: 'ANALISIS DEL ACEITE', frecuencia: true, kilometraje: false },
    { id: '202', tipo: 'PREDICTIVO', descripcion: 'ANALISIS DE DATOS DE SENSORES', frecuencia: true, kilometraje: false },
    { id: '203', tipo: 'PREDICTIVO', descripcion: 'INSPECCION VISUAL AVANZADA', frecuencia: true, kilometraje: false }

];
